apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"creationTimestamp":"2024-05-13T13:35:42Z","labels":{"app":"spring-petclinic-rest"},"name":"spring-petclinic-rest","namespace":"default","resourceVersion":"3734","uid":"b2d8adc5-e15a-4b0f-8003-f500baa02a7b"},"spec":{"allocateLoadBalancerNodePorts":true,"clusterIP":"10.99.177.237","clusterIPs":["10.99.177.237"],"externalTrafficPolicy":"Cluster","internalTrafficPolicy":"Cluster","ipFamilies":["IPv4"],"ipFamilyPolicy":"SingleStack","ports":[{"nodePort":31933,"port":9966,"protocol":"TCP","targetPort":9966}],"selector":{"app":"spring-petclinic-rest"},"sessionAffinity":"None","type":"LoadBalancer"},"status":{"loadBalancer":{}}}
  creationTimestamp: "2024-05-13T14:11:01Z"
  labels:
    app: spring-petclinic-rest
  name: spring-petclinic-rest
  namespace: default
  resourceVersion: "515"
  uid: 82860415-13b9-4181-bbea-af53bf4dd7da
spec:
  allocateLoadBalancerNodePorts: true
  clusterIP: 10.99.177.237
  clusterIPs:
  - 10.99.177.237
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 31933
    port: 9966
    protocol: TCP
    targetPort: 9966
  selector:
    app: spring-petclinic-rest
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer: {}
